version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.9.5
      - test-3.9.4
      - test-3.9.3
      - test-3.9.2
      - test-3.9.1
      - test-3.9.0
      - test-3.8.10
      - test-3.8.9
      - test-3.8.8
      - test-3.8.7
      - test-3.8.6
      - test-3.8.5
      - test-3.8.4
      - test-3.8.3
      - test-3.8.2
      - test-3.8.1
      - test-3.8.0
      - test-3.7.10
      - test-3.7.9
      - test-3.7.8
      - test-3.7.7
      - test-3.7.6
      - test-3.7.5
      - test-3.7.4
      - test-3.7.3
      - test-3.7.2
      - test-3.7.1
      - test-3.7.0
      - test-3.6.8
      - test-3.6.7
      - test-3.6.6
      - test-3.6.5
      - test-3.6.4
      - test-3.6.3
      - test-3.6.2
      - test-3.6.1
      - test-3.6.0
      - test-3.5.10
      - test-3.5.9
      - test-3.5.8
      - test-3.5.7
      - test-3.5.6
      - test-3.5.5
      - test-3.5.4
      - test-3.5.3
jobs:
  test-3.9.5:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - run:
          name: Install coverage and reporter
          command: |
            pip install coverage==5.5
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            coverage run -m unittest -v
            CODE=$?
            coverage xml
            ./cc-test-reporter after-build --exit-code $CODE
  test-3.9.4: &template
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python -m unittest
  test-3.9.3:
    <<: *template
    docker:
      - image: cimg/python:3.9.3
  test-3.9.2:
    <<: *template
    docker:
      - image: cimg/python:3.9.2
  test-3.9.1:
    <<: *template
    docker:
      - image: cimg/python:3.9.1
  test-3.9.0:
    <<: *template
    docker:
      - image: cimg/python:3.9.0
  test-3.8.10:
    <<: *template
    docker:
      - image: cimg/python:3.8.10
  test-3.8.9:
    <<: *template
    docker:
      - image: cimg/python:3.8.9
  test-3.8.8:
    <<: *template
    docker:
      - image: cimg/python:3.8.8
  test-3.8.7:
    <<: *template
    docker:
      - image: cimg/python:3.8.7
  test-3.8.6:
    <<: *template
    docker:
      - image: cimg/python:3.8.6
  test-3.8.5:
    <<: *template
    docker:
      - image: cimg/python:3.8.5
  test-3.8.4:
    <<: *template
    docker:
      - image: cimg/python:3.8.4
  test-3.8.3:
    <<: *template
    docker:
      - image: cimg/python:3.8.3
  test-3.8.2:
    <<: *template
    docker:
      - image: cimg/python:3.8.2
  test-3.8.1:
    <<: *template
    docker:
      - image: cimg/python:3.8.1
  test-3.8.0:
    <<: *template
    docker:
      - image: cimg/python:3.8.0
  test-3.7.10:
    <<: *template
    docker:
      - image: cimg/python:3.7.10
  test-3.7.9:
    <<: *template
    docker:
      - image: cimg/python:3.7.9
  test-3.7.8:
    <<: *template
    docker:
      - image: cimg/python:3.7.8
  test-3.7.7:
    <<: *template
    docker:
      - image: cimg/python:3.7.7
  test-3.7.6:
    <<: *template
    docker:
      - image: cimg/python:3.7.6
  test-3.7.5:
    <<: *template
    docker:
      - image: cimg/python:3.7.5
  test-3.7.4:
    <<: *template
    docker:
      - image: cimg/python:3.7.4
  test-3.7.3:
    <<: *template
    docker:
      - image: cimg/python:3.7.3
  test-3.7.2:
    <<: *template
    docker:
      - image: cimg/python:3.7.2
  test-3.7.1:
    <<: *template
    docker:
      - image: cimg/python:3.7.1
  test-3.7.0:
    <<: *template
    docker:
      - image: cimg/python:3.7.0
  test-3.6.8:
    <<: *template
    docker:
      - image: cimg/python:3.6.8
  test-3.6.7:
    <<: *template
    docker:
      - image: cimg/python:3.6.7
  test-3.6.6:
    <<: *template
    docker:
      - image: cimg/python:3.6.6
  test-3.6.5:
    <<: *template
    docker:
      - image: cimg/python:3.6.5
  test-3.6.4:
    <<: *template
    docker:
      - image: cimg/python:3.6.4
  test-3.6.3:
    <<: *template
    docker:
      - image: cimg/python:3.6.3
  test-3.6.2:
    <<: *template
    docker:
      - image: cimg/python:3.6.2
  test-3.6.1:
    <<: *template
    docker:
      - image: cimg/python:3.6.1
  test-3.6.0:
    <<: *template
    docker:
      - image: cimg/python:3.6.0
  test-3.5.10:
    <<: *template
    docker:
      - image: cimg/python:3.5.10
  test-3.5.9:
    <<: *template
    docker:
      - image: cimg/python:3.5.9
  test-3.5.8:
    <<: *template
    docker:
      - image: cimg/python:3.5.8
  test-3.5.7:
    <<: *template
    docker:
      - image: cimg/python:3.5.7
  test-3.5.6:
    <<: *template
    docker:
      - image: cimg/python:3.5.6
  test-3.5.5:
    <<: *template
    docker:
      - image: cimg/python:3.5.5
  test-3.5.4:
    <<: *template
    docker:
      - image: cimg/python:3.5.4
  test-3.5.3:
    <<: *template
    docker:
      - image: cimg/python:3.5.3
